#!/bin/sh
qemu-system-x86_64 -enable-kvm -m size=1G -smp cpus=2 -display curses \
  -drive if=virtio,file=disk.qcow2,format=qcow2,index=0,media=disk \
  -net nic,name=eth0,model=virtio \
  -net user,name=eth0,hostfwd=::2200-:22
